services:
  backend:
    build: ./backend
    env_file: .env
    volumes:
      - /mnt/media:/mnt/media
      - /mnt/drive_perso/Upload-Assistant-FR:/upload-assistant:ro
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
